# Этап №1: окружение (SDK) для сборки приложения
from mcr.microsoft.com/dotnet/sdk:8.0 as build-env
# рабочая директория внутри контейнера
workdir /app

# Этап №2: копирование файла проекта с хоста в контейнер;
# слой с dotnet restore будет пересобираться только при изменении .csproj (кэширование)
copy *.csproj ./
# восстановление зависимостей проекта
run dotnet restore
# копирование остальных файлов проекта
copy . ./

# Этап №3: сборка приложения и подготовка runtime-набора файлов
run dotnet publish -c Release -o out

# Этап №4: облегченный финальный образ - подключение среды выполнения
from mcr.microsoft.com/dotnet/runtime:8.0
# новая рабочая директория
workdir /app
# копирование результата сборки из build-env (этап №1)
copy --from=build-env /app/out .

# Этап №5: команда выполняемая при запуске контейнера
# (токен передается как переменная окружения через параметр в команде docker run -e TG_BOT_TOKEN)
entrypoint ["dotnet", "EchoBot.dll"]